# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c78786394e312a6158c948120b87f378c6b8273df0704cd56479ce202b76659c1859f663511c9aa0866ab3d2daea50b126dce833ac784066c1c589563f8bf5eb

test:
  secret_key_base: 5ba442e940857c1407cab970d181a9e32e70568588f00958fe6b82dfacfa0d9ffc5044feb5fb835a3f249cd88364f1c217be00dcf5ac4bcfd16867ca877cd9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
