/*Seed data for Suppliers*/

insert into `suppliers` (`id`, `name`, `created_at`) values('1','SJS/สุนีย์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('2','วี.พี.ไวร์เมช', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('3','สหวิริยา', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('4','เอ็ม.อาร์.ที.', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('5','เหล็กสยาม', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('6','ไทยง้วนเมทัล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('7','มหาชัย/ซ้อลัดดา', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('8','ทวีโชคพาณิชย์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('9','ริชสตีล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('10','เอเซียเมทัล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('11','เต็กเฮง', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('12','ไทยเมทัล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('13','อินไซท์สตีล/ซ้อสุจิตรา', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('14','ไทยเมทอล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('15','สตีลวัน จำกัด', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('16','เฮียวีระ', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('17','ซันสตีลกรุ๊ป จำกัด', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('18','เกษมสวัสดิ์โลหะกิจ จำกัด', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('19','ซี.เอส.พี. สตีล เซ็นเตอร์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('20','บางกอกเมทัลคอยล์เซ็นเตอร์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('21','เพิ่มสินสตีลเวิร์ค', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('22','ธนสมบูรณ์สตีล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('23','เพิ่มชัยพานิชย์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('24','เมทัลลิค คอยส์ เซ็นเตอร์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('25','SAMSUNG', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('26','เบเนฟิท บลู', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('27','เหล็กทรัพย์กรุ๊ป', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('28','สยามชัยอินเตอร์เทรด', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('29','สหไทย', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('30','ริช เอเชีย', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('31','เคเอสเอสสตีลพาณิชย์', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('32','สามชัยสตีล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('33','ซินซุ่นหลี', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('34','เค.วัน.เมทอล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('35','เดอะ สตีล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('36','สินกิจไพบูลย์โลหะการ', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('37','เค เจ เบสท์ สตีล', now());
insert into `suppliers` (`id`, `name`, `created_at`) values('38','เมทัลลิค เซคชั่น', now());
